"""added confirmed column

Revision ID: 110097833736
Revises: ce3dbf0c843f
Create Date: 2022-04-05 11:37:24.309756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110097833736'
down_revision = 'ce3dbf0c843f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
